/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as BaseRouteImport } from './app/routes/_base'
import { Route as AuthRouteImport } from './app/routes/_auth'
import { Route as BaseIndexRouteImport } from './app/routes/_base.index'
import { Route as DLayoutRouteImport } from './app/routes/d/_layout'
import { Route as BaseDemoRouteImport } from './app/routes/_base.demo'
import { Route as AuthSignupRouteImport } from './app/routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './app/routes/_auth/signin'
import { Route as DLayoutIndexRouteImport } from './app/routes/d/_layout.index'
import { Route as DLayoutProfileRouteImport } from './app/routes/d/_layout.profile'
import { Route as DLayoutHistoryRouteImport } from './app/routes/d/_layout.history'

const BaseRoute = BaseRouteImport.update({
  id: '/_base',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseIndexRoute = BaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseRoute,
} as any)
const DLayoutRoute = DLayoutRouteImport.update({
  id: '/d/_layout',
  path: '/d',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseDemoRoute = BaseDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => BaseRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const DLayoutIndexRoute = DLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DLayoutRoute,
} as any)
const DLayoutProfileRoute = DLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DLayoutRoute,
} as any)
const DLayoutHistoryRoute = DLayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof BaseIndexRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/demo': typeof BaseDemoRoute
  '/d': typeof DLayoutRouteWithChildren
  '/d/history': typeof DLayoutHistoryRoute
  '/d/profile': typeof DLayoutProfileRoute
  '/d/': typeof DLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof BaseIndexRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/demo': typeof BaseDemoRoute
  '/d/history': typeof DLayoutHistoryRoute
  '/d/profile': typeof DLayoutProfileRoute
  '/d': typeof DLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_base': typeof BaseRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_base/demo': typeof BaseDemoRoute
  '/d/_layout': typeof DLayoutRouteWithChildren
  '/_base/': typeof BaseIndexRoute
  '/d/_layout/history': typeof DLayoutHistoryRoute
  '/d/_layout/profile': typeof DLayoutProfileRoute
  '/d/_layout/': typeof DLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/demo'
    | '/d'
    | '/d/history'
    | '/d/profile'
    | '/d/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/signup' | '/demo' | '/d/history' | '/d/profile' | '/d'
  id:
    | '__root__'
    | '/_auth'
    | '/_base'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_base/demo'
    | '/d/_layout'
    | '/_base/'
    | '/d/_layout/history'
    | '/d/_layout/profile'
    | '/d/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  BaseRoute: typeof BaseRouteWithChildren
  DLayoutRoute: typeof DLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_base': {
      id: '/_base'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_base/': {
      id: '/_base/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BaseIndexRouteImport
      parentRoute: typeof BaseRoute
    }
    '/d/_layout': {
      id: '/d/_layout'
      path: '/d'
      fullPath: '/d'
      preLoaderRoute: typeof DLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_base/demo': {
      id: '/_base/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof BaseDemoRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/d/_layout/': {
      id: '/d/_layout/'
      path: '/'
      fullPath: '/d/'
      preLoaderRoute: typeof DLayoutIndexRouteImport
      parentRoute: typeof DLayoutRoute
    }
    '/d/_layout/profile': {
      id: '/d/_layout/profile'
      path: '/profile'
      fullPath: '/d/profile'
      preLoaderRoute: typeof DLayoutProfileRouteImport
      parentRoute: typeof DLayoutRoute
    }
    '/d/_layout/history': {
      id: '/d/_layout/history'
      path: '/history'
      fullPath: '/d/history'
      preLoaderRoute: typeof DLayoutHistoryRouteImport
      parentRoute: typeof DLayoutRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BaseRouteChildren {
  BaseDemoRoute: typeof BaseDemoRoute
  BaseIndexRoute: typeof BaseIndexRoute
}

const BaseRouteChildren: BaseRouteChildren = {
  BaseDemoRoute: BaseDemoRoute,
  BaseIndexRoute: BaseIndexRoute,
}

const BaseRouteWithChildren = BaseRoute._addFileChildren(BaseRouteChildren)

interface DLayoutRouteChildren {
  DLayoutHistoryRoute: typeof DLayoutHistoryRoute
  DLayoutProfileRoute: typeof DLayoutProfileRoute
  DLayoutIndexRoute: typeof DLayoutIndexRoute
}

const DLayoutRouteChildren: DLayoutRouteChildren = {
  DLayoutHistoryRoute: DLayoutHistoryRoute,
  DLayoutProfileRoute: DLayoutProfileRoute,
  DLayoutIndexRoute: DLayoutIndexRoute,
}

const DLayoutRouteWithChildren =
  DLayoutRoute._addFileChildren(DLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  BaseRoute: BaseRouteWithChildren,
  DLayoutRoute: DLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
